name: Skills
main: skills.Skills
version: 0.1b
description: Skills system
author: Indeleble
depend: [NWCore, PermissionsEx]
commands:
   skills:
      description: Basic skills command
      usage: /skills <ver/aprender> [habilidad]
      permission:
      permission-message: Sin permisos, Hu!Ha!
   pangolin:
      description: Comando no permitido
      usage: /No permitido
      permission:
      permission-message: Comando no permitido